In [27]:
import numpy as np
import pandas as pd

# Read the CSV file into DataFrame
df = pd.read_csv('Iris.csv')

# Drop the 'Id' column and update the DataFrame in place
df.drop(columns=['Id'],axis=1,inplace=True)
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
X=df.iloc[:,0:4] #for all rows and for first 4 cols
Y=df["Species"]
#whenever targets or attributes are not numeric we perform one hot enocding for targets,sklearn does it in the backend for targets so we dont have to do onehotenc for targets while using sklearn 
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, random_state=0)
log = LogisticRegression()
log.fit(X_train,Y_train)
print(log.coef_)#beta1,...beta4
print('############')
print(log.intercept_)#only betazero
prediction=log.predict(X_test)
print(prediction)
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_recall_fscore_support as score
from sklearn.metrics import accuracy_score
# rows actual # columns predicted in sklearn
cnf=confusion_matrix(predictions, Y_test)
print(cnf)

precision,recall,fscore,_=score(Y_test,predictions)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))
print(accuracy_score(Y_test,prediction))

[[-0.41449822  0.84920396 -2.33184383 -0.99147821]
 [ 0.521025   -0.29401477 -0.21784701 -0.71159359]
 [-0.10652679 -0.55518919  2.54969084  1.7030718 ]]
############
[  9.23999169   1.7366026  -10.97659429]
['Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica']


ValueError: Found input variables with inconsistent numbers of samples: [30, 38]

['Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-versicolor' 'Iris-setosa' 'Iris-setosa'
 'Iris-virginica' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica' 'Iris-virginica' 'Iris-versicolor'
 'Iris-setosa' 'Iris-virginica']


ValueError: Found input variables with inconsistent numbers of samples: [30, 38]